### PR TITLE
Change targeting method

### PR DESCRIPTION
**Pull request by darenju**
Hello!

Thank you for this tweak, I’ve searched for something like this today and came across your topic on reddit. Then I managed to find the repo - thank you for making that open source.

However, I’ve found the tweak to not be working on my device: my language is French.

So I forked this and wrote some logs to see how it works. I’ve found a better way to target the "… is typing" notifications. Actually there is a `publisherBulletinID` in the `BBBulletinRequestID` that holds something like `typing~username` and `chat~username`: this is something that does not depend on translation in any way.

I hope you can merge this to allow users all across the globe speaking various languages to hide those notifications :smile:

### CODE REVIEW

**Comment by eclair4151** [comment]
Ah awesome! I will bench test this and merge it/submit it to bigboss sometime this week. Thanks for this!

**Comment by darenju** [comment]
Yes, you should test it a bit more than I did (only with one friend)…

Also, I changed the filter in the `plist`, to watch on `com.apple.bulletinboard` instead of `com.apple.springboard`. I couldn’t log any notification before that change…

Please keep me informed!

**Comment by eclair4151** [comment]
This looks good to me. Thanks for the help!

**Comment by eclair4151** [comment]
i need to do some more testing, The tweak has stopped working for me for some reason. i will look into it later. i merged it for now but have not submitted it to the store. i think it may be because of the changed hook but will check in a bit

**Comment by darenju** [comment]
That’s strange, because it previously didn’t work with the previous bundle filter. Maybe is it because of different versions of iOS? I am using 13.5. 

Tested yesterday again with another friend, only got the chat notifications, no typing ones.

**Comment by eclair4151** [comment]
After some more testing, it seems the plist filter was breaking it for me. Leaving it as springboard and using you new method works, so i am going to change it back to springboard and release it since that seems to have worked for everyone else. I am on iOS 13.5 as well

**Comment by darenju** [comment]
Whatever works for you!

**Comment by darenju** [comment]
@eclair4151 I downloaded and tested new version, it also works on my device. All good!

**Comment by eclair4151** [comment]
Ah great to hear. Thanks again for making this PR I appreciate it a lot!

**Comment by eclair4151** [comment]
Random note, i figured out why it wasn't working for me earlier. When it is a group chat, the message starts with "mischief_typing" instead. i have updated the tweak to 0.0.4 with the fix and submitted to bigboss

**Comment by darenju** [comment]
Hey I just noticed the update and was coming here to see how you made it. Glad it works now! I’m not in any group chat, so couldn’t tell.

**Pull request merged**
